# Rename to build stable version
# This is stable version
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "je_api_testka"
version = "0.0.105"
authors = [
    { name = "JE-Chen", email = "zenmailman@gmail.com" },
]
description = "APT Testing Automation Framework"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = [
    "requests",
    "Flask"
]
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Win32 (MS Windows)",
    "Environment :: MacOS X",
    "Environment :: X11 Applications",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/JE-Chen/APITestka"

[tool.setuptools.packages]
find = { namespaces = false }