name: APITestka Stable Python3.9

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_stable_version:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      # request test
      - name: Test requests AJAX Request
        run: python ./test/requests/unit_test/ajax/test_ajax_requests.py
      - name: Test requests Request Delete
        run: python ./test/requests/unit_test/api_delete/test_request_delete.py
      - name: Test requests Get All Data
        run: python ./test/requests/unit_test/api_get/test_api_get_all_data.py
      - name: Test requests GET Method
        run: python ./test/requests/unit_test/api_get/test_request_get.py
      - name: Test requests HEAD Method
        run: python ./test/requests/unit_test/api_head/test_request_head.py
      - name: Test requests OPTIONS Method
        run: python ./test/requests/unit_test/api_options/test_request_options.py
      - name: Test requests PATCH Method
        run: python ./test/requests/unit_test/api_patch/test_request_patch.py
      - name: Test requests POST Method
        run: python ./test/requests/unit_test/api_post/test_request_post.py
      - name: Test requests PUT Method
        run: python ./test/requests/unit_test/api_put/test_request_put.py
      - name: Test requests Session
        run: python ./test/requests/unit_test/api_session/test_request_session.py
      - name: Test requests Process Json
        run: python ./test/requests/unit_test/json/json_reformat_test/test_json_process.py
      - name: Test requests Read And Write And Reformat Json
        run: python ./test/requests/unit_test/json/rw_and_reformat_json_test/rw_and_reformat_json_test.py
      - name: Test requests Generate Json Report
        run: python ./test/requests/unit_test/generate_report/json_report_test.py
      - name: Test requests Generate HTML Report
        run: python ./test/requests/unit_test/generate_report/html_report_test.py
      - name: Test requests Execute Action
        run: python ./test/requests/unit_test/executor_test/execute_action_test.py
      - name: Test requests Get Dir Files And Execute
        run: python ./test/requests/integrated_test/get_dir_file_and_execute/get_dir_file_and_execute.py
      - name: Test requests XML Module
        run: python ./test/requests/unit_test/xml/xml_test.py
      - name: Test requests Soap Data To Dict
        run: python ./test/requests/integrated_test/soap_to_dict_test/soap_to_dict_test.py
      - name: Test requests Generate XML Report
        run: python ./test/requests/unit_test/generate_report/xml_report_test.py
      - name: Test requests Get Soap Data
        run: python ./test/requests/unit_test/soap_test/soap_test.py
      - name: Test requests Argparse
        run: python ./test/requests/unit_test/argparse/argparse_test.py
      - name: Test requests Compare
        run: python ./test/requests/unit_test/compare_test/compare_test.py
      - name: Test requests Callback
        run: python ./test/requests/unit_test/callback/callback_test.py
      - name: Test requests Create Project
        run: python ./test/requests/unit_test/create_project/create_project.py
      - name: Test requests Interval Scheduler
        run: python ./test/requests/unit_test/scheduler_test/sec_interval_test.py
      - name: Test requests Cron Scheduler
        run: python ./test/requests/unit_test/scheduler_test/sec_cron_test.py
      # httpx test
      - name: Test httpx AJAX Request
        run: python ./test/httpx/sync/unit_test/ajax/test_ajax_requests.py
      - name: Test httpx Request Delete
        run: python ./test/httpx/sync/unit_test/api_delete/test_request_delete.py
      - name: Test httpx Get All Data
        run: python ./test/httpx/sync/unit_test/api_get/test_api_get_all_data.py
      - name: Test httpx GET Method
        run: python ./test/httpx/sync/unit_test/api_get/test_request_get.py
      - name: Test httpx HEAD Method
        run: python ./test/httpx/unit_test/api_head/test_request_head.py
      - name: Test httpx OPTIONS Method
        run: python ./test/httpx/sync/unit_test/api_options/test_request_options.py
      - name: Test httpx PATCH Method
        run: python ./test/httpx/sync/unit_test/api_patch/test_request_patch.py
      - name: Test httpx POST Method
        run: python ./test/httpx/sync/unit_test/api_post/test_request_post.py
      - name: Test httpx PUT Method
        run: python ./test/httpx/sync/unit_test/api_put/test_request_put.py
      - name: Test httpx Session
        run: python ./test/httpx/sync/unit_test/api_session/test_request_session.py
      - name: Test httpx Generate Json Report
        run: python ./test/httpx/sync/unit_test/generate_report/json_report_test.py
      - name: Test httpx Generate HTML Report
        run: python ./test/httpx/sync/unit_test/generate_report/html_report_test.py
      - name: Test httpx Execute Action
        run: python ./test/httpx/sync/unit_test/executor_test/execute_action_test.py
      - name: Test httpx Get Dir Files And Execute
        run: python ./test/httpx/sync/integrated_test/get_dir_file_and_execute/get_dir_file_and_execute.py
      - name: Test httpx Generate XML Report
        run: python ./test/httpx/sync/unit_test/generate_report/xml_report_test.py
      - name: Test httpx Compare
        run: python ./test/httpx/sync/unit_test/compare_test/compare_test.py
      # httpx async test
      - name: Test httpx async AJAX Request
        run: python ./test/httpx/async/unit_test/ajax/test_ajax_requests.py
      - name: Test httpx async Request Delete
        run: python ./test/httpx/async/unit_test/api_delete/test_request_delete.py
      - name: Test httpx async Get All Data
        run: python ./test/httpx/async/unit_test/api_get/test_api_get_all_data.py
      - name: Test httpx async GET Method
        run: python ./test/httpx/async/unit_test/api_get/test_request_get.py
      - name: Test httpx async HEAD Method
        run: python ./test/httpx/unit_test/api_head/test_request_head.py
      - name: Test httpx OPTIONS Method
        run: python ./test/httpx/async/unit_test/api_options/test_request_options.py
      - name: Test httpx async PATCH Method
        run: python ./test/httpx/async/unit_test/api_patch/test_request_patch.py
      - name: Test httpx async POST Method
        run: python ./test/httpx/async/unit_test/api_post/test_request_post.py
      - name: Test httpx async PUT Method
        run: python ./test/httpx/async/unit_test/api_put/test_request_put.py
      - name: Test httpx async Session
        run: python ./test/httpx/async/unit_test/api_session/test_request_session.py
      - name: Test httpx async Generate Json Report
        run: python ./test/httpx/async/unit_test/generate_report/json_report_test.py
      - name: Test httpx async Generate HTML Report
        run: python ./test/httpx/async/unit_test/generate_report/html_report_test.py
      - name: Test httpx async Execute Action
        run: python ./test/httpx/async/unit_test/executor_test/execute_action_test.py
      - name: Test httpx async Generate XML Report
        run: python ./test/httpx/async/unit_test/generate_report/xml_report_test.py
      - name: Test httpx async Compare
        run: python ./test/httpx/async/unit_test/compare_test/compare_test.py